/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DataTruncation;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author septi
 */
public class TimPage extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = Koneksi.Koneksi.Koneksi();
    /**
     * Creates new form TimPage
     */
    public TimPage() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\septi\\Pictures\\football.png");
        setIconImage(icon);
        setTitle("FUTSALMATCHFINDER Admin");
        judul();
        tampilData();
        namaCustomer();
    }
    
    public void judul(){
        Object[] judul = {
            "ID TIm", "Nama Tim", "Lokasi Tim", "Jadwal Tim", "No Telp", "Nama Customer"
        };
            tabModel = new DefaultTableModel(null, judul);
            TabelData.setModel(tabModel);
    }
    public void clear(){
        tf_id.setText("");
        tf_namaTim.setText("");
        tf_lokasiTim.setText("");
        dc_jadwal.setDateFormatString("");
        tf_telpTim.setText("");
    }
    public void tampilData(){
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tim ");
    
            while (rs.next()) {
            Object[] data = {
                rs.getString("id_tim"),
                rs.getString("nama_tim"),
                rs.getString("lokasi_tim"),
                rs.getString("jadwal"),
                rs.getString("telp_tim"),
                rs.getString("nama_customer"),
            };
                tabModel.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    public void namaCustomer(){
        try{
            st = cn.createStatement();
            String s = "SELECT nama_customer FROM customer order by nama_customer";
            rs = st.executeQuery(s);
            while (rs.next()){
                Object[] ob = new Object[3];
                ob[0] = rs.getString(1);
                
                cb_customer.addItem((String) ob[0]);
            }
            rs.close();st.close();
        }catch(Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_namaTim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_lokasiTim = new javax.swing.JTextField();
        tf_telpTim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dc_jadwal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_main = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_customer = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 161, 215));

        TabelData.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Tim", "Lokasi Tim", "Jadwal Tim", "No Telp ", "null"
            }
        ));
        TabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelData);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Tim");

        tf_namaTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama Tim");

        tf_lokasiTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_lokasiTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lokasiTimActionPerformed(evt);
            }
        });

        tf_telpTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Lokasi Tim");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID Tim");

        dc_jadwal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dc_jadwalPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Jadwal Tim");

        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_reset.setText("Reset");
        bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resetActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_main.setText("Kembali Ke Menu Utama");
        bt_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mainActionPerformed(evt);
            }
        });

        tf_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("No Telp");

        cb_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilh Nama Customer" }));
        cb_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_customerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nama Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_update, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(bt_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(bt_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(287, 287, 287)
                        .addComponent(bt_main)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(tf_telpTim, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(dc_jadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(tf_lokasiTim, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(tf_namaTim, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(tf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(cb_customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_namaTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tf_lokasiTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_telpTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_main, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_lokasiTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lokasiTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lokasiTimActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            System.out.println("berhasil");
            dc_jadwal.setDateFormatString("yyyy MMMM dd");
            java.sql.Date jadwal = new java.sql.Date(dc_jadwal.getDate().getTime());
            st.executeUpdate("INSERT INTO tim VALUES('" + tf_id.getText() + "','" 
                + tf_namaTim.getText() + "','"
                + tf_lokasiTim.getText() + "','"
                + tf_telpTim.getText() + "','"
                + jadwal + "','"
                + cb_customer.getSelectedItem() +"')");
            tampilData();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            clear();
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_bt_resetActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int jawab;
    
                if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == JOptionPane.YES_OPTION) {
                    st = cn.createStatement();
                    st.executeUpdate("DELETE FROM tim WHERE id_tim='"
                    + tabModel.getValueAt(TabelData.getSelectedRow(), 0) + "'");
                    tampilData();
                clear();
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mainActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(
            null,"Kembali Ke Halaman Utama?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if(reply==JOptionPane.YES_OPTION){
            new MainPage().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bt_mainActionPerformed

    private void dc_jadwalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dc_jadwalPropertyChange
        // TODO add your handling code here:
        if(dc_jadwal.getDate()!=null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String jadwal = sdf.format(dc_jadwal.getDate());
        }
    }//GEN-LAST:event_dc_jadwalPropertyChange
    
    private void TabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataMouseClicked
        // TODO add your handling code here:
        tf_id.setText(TabelData.getValueAt(TabelData.getSelectedRow(),0).toString());
        tf_namaTim.setText(TabelData.getValueAt(TabelData.getSelectedRow(),1).toString());
        tf_lokasiTim.setText(TabelData.getValueAt(TabelData.getSelectedRow(),2).toString());
        dc_jadwal.setDateFormatString(TabelData.getValueAt(TabelData.getSelectedRow(),3).toString());
        tf_telpTim.setText(TabelData.getValueAt(TabelData.getSelectedRow(),4).toString());
        cb_customer.setSelectedItem(TabelData.getValueAt(TabelData.getSelectedRow(),5).toString());
        bt_simpan.setEnabled(true);
        bt_update.setEnabled(true);
        bt_hapus.setEnabled(true);
    }//GEN-LAST:event_TabelDataMouseClicked

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        try {
            st = cn.createStatement();
            System.out.println("Update");
            st.executeUpdate("UPDATE tim set "
                + "nama_tim='"       + tf_namaTim.getText() + "',"
                + "lokasi_tim='"   + tf_lokasiTim.getText() + "', "
                + "telp_tim='"     + tf_telpTim.getText() + "',"
                + "jadwal='"       + dc_jadwal.getDateFormatString() + "',"
                + "nama_customer='"       + cb_customer.getSelectedItem() + "'"
                + "WHERE id_tim = " + tf_id.getText() +"") ;
            tampilData();
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal");
            e.printStackTrace();
            
        }  
    }//GEN-LAST:event_bt_updateActionPerformed

    private void cb_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelData;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_main;
    private javax.swing.JButton bt_reset;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_update;
    private javax.swing.JComboBox<String> cb_customer;
    private com.toedter.calendar.JDateChooser dc_jadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_lokasiTim;
    private javax.swing.JTextField tf_namaTim;
    private javax.swing.JTextField tf_telpTim;
    // End of variables declaration//GEN-END:variables

    private void VALUES(String __nama__lokasi__telp__jadwal__) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
